feat: 도서 정보 삭제 기능 및 API 구현
Kernel360/E2E1-Boogle pull request #64
Opened 2023-10-27 07:31 UTC by RossKWSang

리디렉팅 되지 않는 부분을 수정하고 페이지네이션과 연동되는 코드를 작성했습니다.

도서 정보 삭제시 알림 메시지가 송출됩니다.

2023-10-27 07:41 UTC, GBGreenBravo requested changes
BookController.java에서 BookServiceImpl 사용하지 않고 BookService 사용하시기를 권장드립니다.

2023-10-27 07:51 UTC, linglong67 requested changes
리뷰 확인부탁드려요

2023-10-27 07:51 UTC, linglong67 commented on src/main/java/com/kernel360/boogle/book/model/BookDTO.java
> +    @Transient
이 어노테이션은 어떤 의미인가요?

그리고 현재 기준으로 변경했을 때, 그전까지 구현된 다른 기능에 이슈 없는 부분 체크하셨을까요?

2023-10-27 07:51 UTC, linglong67 commented on src/main/resources/templates/mainPage.html
> +                alert('도서 정보 삭제 중 오류가 발생했습니.');다
이거 글자 깨졌어요! (1)

2023-10-27 07:51 UTC, linglong67 commented on src/main/resources/templates/mainPage.html
> +              alert('도서 정보 삭제 중 오류가 발생했습니.');다
이거 글자 깨졌어요! (2)

2023-10-27 09:28 UTC, RossKWSang commented on src/main/resources/templates/mainPage.html
> +                alert('도서 정보 삭제 중 오류가 발생했습니.');다
수정했습니다.

2023-10-27 09:28 UTC, RossKWSang commented on src/main/resources/templates/mainPage.html
> +              alert('도서 정보 삭제 중 오류가 발생했습니.');다
수정했습니다.

2023-10-27 10:08 UTC, RossKWSang commented on src/main/java/com/kernel360/boogle/book/model/BookDTO.java
> +    @Transient
해당 어노테이션은 엔티티와 테이블간의 매핑시 처리를 하지 않는 멤버변수에 두는 것입니다.

하지만 삭제 이후 기능을 테스트 해보았을때 불필요한 것으로 판명이나 이를 삭제한 코드를 커밋하였습니다.

2023-10-30 01:12 UTC, linglong67 approved these changes
확인했습니다~!

2023-10-30 01:27 UTC, GBGreenBravo approved these changes

2023-10-30 01:37 UTC, merged